'''print("hello")
a=2;
b=3;
sum=a+b
print("sum",sum)

a=int(input("enter a first num: "))
b=int(input("enter second num: "))
sum=a+b
print("sum of two nums : ", sum)

my_list=[1,2,3,"hello",5.6]
print(my_list)
print(my_list[0])

my_tuple=[1,2,3,"hello"] #tuple is immutable means content cannt be changed
print(my_tuple)

my_set={1,2,3,4} #set is an unordered collection of unique elements and doesn't allow elements
my_set.add(5) #adds an element
my_set.remove(3) #removes an element
print(my_set)'''

'''my_dict={"name":"Zakir","age":23} #dictionary is collectoin of key value pairs
my_dict["age"]=24
my_dict["city"]="kupwara"
print(my_dict)
print(len(my_dict))'''


#right angled triangle
'''print()
rows = 20
for i in range (1, rows+1):
    print("*" * i)
print()'''

'''import keyword
print(keyword.kwlist)'''

'''array = [1,4,5,6,2]
array.sort()
print(array)'''

'''a = "hello"
print(a.capitalize())'''

a=256
b=256
print(a is b)

x=257
y=257
print(y is x)